<!DOCTYPE html>
<html>
<head>
  <meta charSet='utf-8' />
  <title>{{config.title + ' - ' + page.title}}</title>
  <link href='https://cdnjs.cloudflare.com/ajax/libs/normalize/4.0.0/normalize.min.css' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,300,700' rel='stylesheet' type='text/css'>
  <link href='{{ url_for("css/docs.css") }}' rel='stylesheet'>
  <style>
  a{ font-size:16px}
  /* 配置此网页默认超链接字体大小为16px */

  </style>
</head>
<body>
  <div class='index'>
    <a href="/介绍.html">
      Open ZINX
    </a>
  </div>
</body>
</html>
